# Generated by Django 6.0.2 on 2026-02-27 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], db_index=True, default='ACTIVE', max_length=20)),
                ('fine_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('book_copy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_records', to='books.bookcopy')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='users.memberprofile')),
            ],
            options={
                'permissions': [('can_borrow_book', 'Can borrow book')],
            },
        ),
    ]
